apiVersion: batch/v1
kind: CronJob
metadata:
  name: simplefin-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: simplefin-exporter
    app.kubernetes.io/component: financial-exporter
spec:
  schedule: "0 6 * * *"  # Run daily at 6 AM
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: simplefin-exporter
            app.kubernetes.io/component: financial-exporter
        spec:
          restartPolicy: OnFailure
          containers:
          - name: simplefin-exporter
            image: simplefin-bridge-exporter:latest
            imagePullPolicy: IfNotPresent  # Use local image since we built it locally
            command: ["/bin/sh"]
            args:
            - "-c"
            - |
              # Start the exporter in the background
              /simplefin-bridge-exporter -setupToken "$SIMPLEFIN_SETUP_TOKEN" &
              
              # Wait for the exporter to be ready
              sleep 10
              
              # Keep the pod alive for 5 minutes to allow Prometheus to scrape
              # (ServiceMonitor scrapes every 30s, so 5 minutes ensures multiple scrapes)
              echo "SimpleFIN exporter started, sleeping for 5 minutes to allow scraping..."
              sleep 300  # 5 minutes
              
              echo "Shutting down after scrape window"
            env:
            - name: SIMPLEFIN_SETUP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: simplefin-config
                  key: setup-token
            ports:
            - containerPort: 8000
              name: metrics
            resources:
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "128Mi"
                cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: simplefin-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: simplefin-exporter
    app.kubernetes.io/component: financial-exporter
spec:
  ports:
  - port: 8000
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app.kubernetes.io/name: simplefin-exporter
    app.kubernetes.io/component: financial-exporter