apiVersion: v1
kind: Secret
metadata:
  name: simplefin-config
  namespace: monitoring
  labels:
    app.kubernetes.io/name: simplefin-exporter
    app.kubernetes.io/component: financial-exporter
type: Opaque
stringData:
  # Demo token from SimpleFIN - replace with your actual token later
  setup-token: "aHR0cHM6Ly9iZXRhLWJyaWRnZS5zaW1wbGVmaW4ub3JnL3NpbXBsZWZpbi9jbGFpbS9ERU1P"