apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simplefin-exporter
  annotations:
    argocd.argoproj.io/manifest-generate-paths: "simplefin-exporter/base"
spec:
  project: default
  source:
    repoURL: 'https://github.com/han-steve/homelab.git'
    targetRevision: HEAD
    path: simplefin-exporter/base
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: simplefin-config
      jsonPointers:
        - /data
        - /stringData
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true