apiVersion: v1
kind: Service
metadata:
  name: ocis
  namespace: ocis
  labels:
    app: ocis
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.20
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
      name: https
  selector:
    app: ocis
